### ISSUE TITLE
Update Flutter to version 3.24.2

### ISSUE THREAD

**Issue by kanghk21** [instrumentisto/flutter-docker-image#17]
Can update Flutter to version 3.24.2 ?
Thanks.

**Comment by tyranron** [comment]
@kanghk21 fixed with https://github.com/instrumentisto/flutter-docker-image/commit/664d75a063511c8c053b1d9763cfeef2d97b3363

You shouldn't really create a new issue for every new Flutter release. I'm subscribed to Flutter releases via RSS, so do expect the update of the image in 1-2 working days after Flutter release.
